### ISSUE TITLE
Socket broken in OSMPCNetworkProxy

### ISSUE THREAD

**Issue by haoyuanying** [OpenSimulationInterface/osi-sensor-model-packaging#28] opened 2018-03-22 15:08 UTC
I am testing the OSMPCNetworkProxy FMU. 

Setup:
1. We have a FMU hoster on our simulator and does the communication (message send & retrieve) with the OSMPCNetworkProxy FMU. A small dummy program is written to continously send data to the FMU to be sent out further via socket.
2. We made a pl written server to check if a server can receive data from the OSMPCNetworkProxy FMU.
3. Built and ran on Ubuntu 16.04.03, gcc-5.

Problem:
After sent a few packets (I guess only the header + 1 or 2 payloads) through the FMU, the socket is down, and the FMU crashed. To solve the issue, we had to close the socket and re-connect the socket to send the payload packet. After sending the packet successfully, we had to close the socket. Code exapmle:

        			close_tcp_proxy_connection(component);
				if (ensure_tcp_proxy_connection(component))
				{
                    	               sendval=send(component->tcp_proxy_socket,(char*)buffer,buffersize,0);
                    	               close_tcp_proxy_connection(component);
				}
				else
				{
					printf("connection cannot be re-established\n");
				}

Question:
Do we do something wrong? Or it is potentially a bug to fix? @pmai @CarloVanDriestenBMW

**Comment by pmai** [comment] 2018-03-22 19:44
It is hard to say anything without more information: What does the log file say? Does the FMU crash (i.e. segfault), or does it continue in an error cycle, or hang, or...? Could you provide the test server and/or dummy program used to run this, so that I could try to reproduce the problem?

Given that the FMU code normally automatically closes and reconnects the socket if one of the send commands fails, changing to code like in the example should not make any difference. Is the code on the other side reading all of the information correctly?

**Comment by haoyuanying** [comment] 2018-03-23 08:56
Forgot to mention about logging:
If we select the public logging via CMake GUI, we received an build error:

Scanning dependencies of target OSMPCNetworkProxy
[ 98%] Building C object OSMPCNetworkProxy/CMakeFiles/OSMPCNetworkProxy.dir/OSMPCNetworkProxy.c.o
In file included from /home/hying/BMW-ascgit-repos/repo-232/NetworkProxyFMU/3456/examples/OSMPCNetworkProxy/OSMPCNetworkProxy.c:11:0:
/home/hying/BMW-ascgit-repos/repo-232/NetworkProxyFMU/3456/examples/OSMPCNetworkProxy/OSMPCNetworkProxy.h: In function ‘internal_log’:
/home/hying/BMW-ascgit-repos/repo-232/NetworkProxyFMU/3456/examples/OSMPCNetworkProxy/OSMPCNetworkProxy.h:165:5: warning: implicit declaration of function ‘vsnprintf’ [-Wimplicit-function-declaration]
     vsnprintf(buffer, 1024, format, arg);
     ^
/home/hying/BMW-ascgit-repos/repo-232/NetworkProxyFMU/3456/examples/OSMPCNetworkProxy/OSMPCNetworkProxy.h:177:9: error: ‘loggingOn’ undeclared (first use in this function)
     if (loggingOn && loggingCategories.count(category))
         ^
/home/hying/BMW-ascgit-repos/repo-232/NetworkProxyFMU/3456/examples/OSMPCNetworkProxy/OSMPCNetworkProxy.h:177:9: note: each undeclared identifier is reported only once for each function it appears in
/home/hying/BMW-ascgit-repos/repo-232/NetworkProxyFMU/3456/examples/OSMPCNetworkProxy/OSMPCNetworkProxy.h:177:22: error: ‘loggingCategories’ undeclared (first use in this function)
     if (loggingOn && loggingCategories.count(category))
                      ^
/home/hying/BMW-ascgit-repos/repo-232/NetworkProxyFMU/3456/examples/OSMPCNetworkProxy/OSMPCNetworkProxy.h:178:9: error: ‘functions’ undeclared (first use in this function)
         functions.logger(functions.componentEnvironment,instanceName.c_str(),fmi2OK,cate
         ^
/home/hying/BMW-ascgit-repos/repo-232/NetworkProxyFMU/3456/examples/OSMPCNetworkProxy/OSMPCNetworkProxy.h:178:57: error: ‘instanceName’ undeclared (first use in this function)
         functions.logger(functions.componentEnvironment,instanceName.c_str(),fmi2OK,cate
                                                         ^
OSMPCNetworkProxy/CMakeFiles/OSMPCNetworkProxy.dir/build.make:62: recipe for target 'OSMPCNetworkProxy/CMakeFiles/OSMPCNetworkProxy.dir/OSMPCNetworkProxy.c.o' failed
make[2]: *** [OSMPCNetworkProxy/CMakeFiles/OSMPCNetworkProxy.dir/OSMPCNetworkProxy.c.o] Error 1
CMakeFiles/Makefile2:461: recipe for target 'OSMPCNetworkProxy/CMakeFiles/OSMPCNetworkProxy.dir/all' failed
make[1]: *** [OSMPCNetworkProxy/CMakeFiles/OSMPCNetworkProxy.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

The private logging is defautly selected, but the log file was not created in the defined path.

FMU Crash:
No segmentation fault, the FMU simply got killed as well as the host (wrapper) program. If the connection betwwen FMU and the dummy server was not set, the host program with FMU was running looply as expected.

Dummy Server:

use IO::Socket::INET;
$| = 1;
my $socket = new IO::Socket::INET (
    LocalHost => '127.0.0.1',
    LocalPort => '3456',
    Proto => 'tcp',
    Listen => 5,
    Reuse => 1
);
die "cannot create socket $!\n" unless $socket;
print "server waiting for client connection on port 3456\n";

my $recvctnr = 0;
 
while(1)
{
    # waiting for a new client connection
    my $client_socket = $socket->accept();
 
    # get information about a newly connected client
    my $client_address = $client_socket->peerhost();
    my $client_port = $client_socket->peerport();
    print "connection from $client_address:$client_port\n";
 
    # read up to 1024 characters from the connected client
    my $data = "";
    $client_socket->recv($data, 999999999);
    
    $recvctnr++;
    
    print "received data: $recvctnr\n";
 
    # write response data to the connected client
    $data = "ok";
    $client_socket->send($data);
 
    # notify client that response has been sent
    shutdown($client_socket, 1);
}
 
$socket->close();

If we did the change as I gave in the above comments in the OSMPCNetworkProxy.c code, we received the correct data. BTW, the FMU (with host) & Dummy Server are on the same computer.

**Comment by pmai** [comment] 2018-03-23 09:53
The PUBLIC logging problem is a bug (leftover from C++ code), will be fixed in next release. The private logging is however not on by default (i.e. please make sure that PRIVATE_LOGGING really is ON in CMake), and when testing on Linux I do get a corresponding log file in /tmp/OSMPCNetworkProxyLog.log. If this is not happening for you, something is deeply corrupted somewhere.

The receiving code seems somewhat suspect: You need to ensure that you read the proper number of bytes from the socket each time (i.e. 32bit signed interger for the length field, then the number of bytes that this length field indicates). If this is not done properly, then the TCP stream will likely back-up. Note that you are not assured that recv will not return early.

Forcing a socket close on the sender side will definitely clear up problems on the receiver side, since this will create a new connection. However this is not what you want in production code (TCP socket setup is expensive in terms of latency).

If you could provide your FMU runner code, I can try to replicate and debug your issues further.

**Comment by haoyuanying** [comment] 2018-03-23 10:01
We tried to put ON for private logging in the CMakeLists.txt and also through the CMake GUI, but no logging files got generated.

We will check against the no. of byte in the receiver.

I agree with you that re-creating a socket is expensive in terms of latency.

If @CarloVanDriestenBMW agrees, we can provide the runner code...

**Comment by pmai** [comment] 2018-03-23 10:36
When testing on Ubuntu 16.04.2 I don't see any problems with private logging not being available (as long as the user has rights to create files in /tmp/, which should be no problem).

For simple tests using something like socat or ncat should be sufficient, e.g. using ncat (available with apt install nmap under Ubunut 16.04):

    ncat -l 3456 --keep-open --exec "/bin/cat"

 or using socat (available with apt install socat):

    socat TCP4-LISTEN:3456,fork EXEC:cat

should just work.

**Comment by pmai** [comment] 2018-03-23 11:25
BTW, I overlooked this in the initial analysis: The demo server code is of course broken, in that it does not properly send data back to the FMU: Instead of sending a 32bit signed length field, it just sends the OK data payload directly, which will of course cause problems/errors. The code also only does one round-trip, but does not close the client socket, which can of course also cause the connection to hang.

If I fix those issues, the demo code seems to work alright (note the code below doesn't fix the proper receiving with recv, which needs to keep track of the length field and account for short reads, i.e. basic TCP handling):

    ...
    print "connection from $client_address:$client_port\n";
    
    while(1)
    {
        # read up to 1024 characters from the connected client
        my $data = "";
        $client_socket->recv($data, 999999999);

        $recvctnr++;
        
        print "received data: $recvctnr\n";
        # write response data to the connected client
        my $senddata = pack("l</a*","ok");
        $client_socket->send($senddata);
    }
    ...

**Comment by pmai** [comment] 2018-03-23 11:32
FWIW I'd still like to see the running code, since even with these bugs in the receiving side, the FMU handles this in my testing with properly logged errors and automatic socket close/reopen, as it should...

**Comment by haoyuanying** [comment] 2018-03-23 12:24
Using ncat -l 3456 --keep-open --exec "/bin/cat", we are able to transfer data via FMU (with host) out, the socket is not broken and we do not have to restart the socket as the initial example. However, using the above demo server, we still encounter the same problem...

**Comment by pmai** [comment] 2018-03-23 12:49
As I said, without the exact code running (i.e. runner code), I can't really help very well. That said, I think fixing up the recv calls might help (currently only one recv is issued, but since this can return early - i.e. only after the header is read, due to timing issues, this can cause the hang). The Perl Socket API is IMHO attrocious, so I'm not going to try to write robust code here, but the following change might make this a bit more workable:

    ...
    while(1)
    {
        # read up to 1024 characters from the connected client
        my $countdata = "";
        $client_socket->recv($countdata, 4);
        printf "Read message length field is %d bytes.\n", length $countdata;
        my $count = unpack("l>",$countdata);
        print "Read message length is $count\n";
        my $data ="";
        $client_socket->recv($data, $count) unless $count == 0;
        
        $recvctnr++;
        
        print "received data: $recvctnr\n";

        # write response data to the connected client
        my $senddata = pack("l</a*","ok");
        $client_socket->send($senddata);
    }

**Comment by pmai** [comment] 2018-05-14 23:01
Closing the issue since no further reproducible problem has been reported.

**Closed as completed by pmai** 2018-05-14 23:01 UTC
