### ISSUE TITLE
Communication problem when FMUs run in separate processes

### ISSUE THREAD

**Issue by JJochheim** [OpenSimulationInterface/osi-sensor-model-packaging#17] opened 2017-04-27 15:37 UTC
The current approach to exchange sensor data that is specified and serialized with OSI between FMUs uses shared memory to transfer the data between the FMUs.
This approach does not work when the FMUs run in separate processes because shared memory is by default not available between processes. This results in access violations in the FMU that receives the data. Workarounds for this are possible but require additional specifications for the FMU.
We are happy to discuss possible solutions for this problem.

**Comment by pmai** [comment] 2017-04-27 17:43
Hi,

with regards to FMUs running in separate processes the environment needs to treat the binary inputs/outputs in the same way it treats string inputs/outputs, modulo the longer lifetimes specced for OSMP.  We are actually running OSMP FMUs in separate processes this way today. That said feel free to contact me directly to discuss this issue in more detail...

Due to the desire to add binary types to FMI directly and for other use cases I'm planning to add standardised annotations to the binary variables to indicate their binariness more explicitly rather than only relying on the minimalist name-based specification currently defined...

**Comment by JJochheim** [comment] 2017-04-28 14:56
Dear Mr. Mai

Thank you for your quick reply. I am not sure whether I understand your proposed solution correctly. Could you describe a little bit further what you have in mind?

Mr. van Driesten already informed us that you want to contact the FMI project for a future extension of the standard. We also informed our colleague Mr. Pillekeit about this activity to support us in the discussion with the FMI project.

**Comment by pmai** [comment] 2017-04-28 16:52
Take the situation for a string input of a normal FMU: If the FMU is run in a separate process (without shared memory) then the environment running the FMU will have to somehow transport the string into the process (e.g. via socket communications), reconstitute the string buffer, and pass the address of the new string into the FMU via fmi2SetString, and not the original pointer only valid in the original process (whether originated in the environment or in another FMU process).

An environment supporting OSMP Binary inputs/outputs with seperate address spaces (e.g. processes without shared memory) needs to do this special treatment for binary inputs/outputs as well: I.e. für an input transmit the original memory into the destination process through some means, then provide the address of this new buffer to the FMU in the relevant fmi2SetInteger calls. Due to the lifecycle requirements the new buffers need to be kept around a bit longer (past the end of the next DoStep), but in principle it's the same mechanism as for Strings. For binary outputs it's the reverse: Take the memory buffer returned by the FMU and transport its contents outside the process, then use the new address for later accesses.

Currently (I.e. for OSMP 0.2.1) the environment can detect the integer variables that actually represent binary variables through the specified names (I.e. OSMPSensorData(In|Out)(\[[0-9]+\])?\.(base\.lo|base\.hi|size) in regexp ). Since the basic concept however makes sense beyond sensor data, and since in the future we want binary data types in FMI directly, I would amend the OSMP spec to directly include OSMP annotations on the relevant variables to indicate their binaryness regardless of their naming. This should make the mechanism more flexible.

As an example, we use a protocol (RFMI) we developed to allow the remote execution of FMUs on different nodes (e.g. To also allow cross-OS support, so that a pure windows FMU can be used by a pure Linux simulation environment). Hence no shared memory is available. For OSMP Support we detect the binary variables ( we actually rewrite our internal FMU meta-data so that the three integer variables get turned into the one binary variable that's actually intended) and then handle them similarly to string variables (putting the binary content onto the wire and not the pointers).

For systems with separate processes but that could use shared memory for IPC you can try to play some tricks to reduce copying, however that is limited since you currently cannot command the FMU to place its output buffers at a predetermined location. We could think about ways of doing this, but I fear the complexity is seldom worthwhile in terms of performance and it will be even harder to get something like this into the FMI standard...

So in essence treat the osmp variables like they were proper binary variables (with fmi2Get/SetBinary) etc. (which they will become if the planned FCP is successful) and the 3 integer vars are just a funny encoding;).

**Comment by JJochheim** [comment] 2017-05-04 09:00
Dear Mr. Mai,

Thank you for your extensive reply and the good explanations. I think you are describing some promising approaches to handle the communication between FMUs that run in separate processes and it is good to know that you have already tried out this scenario. 
We will do some investigations to find a way that is working in our toolchain and come back to you as soon as we have more information.

**Comment by JJochheim** [comment] 2017-06-02 14:30
Dear Mr. Mai,

As you might have already heard, we have now developed a temporary workaround that allows us to use OSI for the communication between different processes. In principial, we established a shared memory between the two elements so that the receiving process has the data in its own memory.
Thank you for your fast responses.

**Comment by pmai** [comment] 2018-02-15 16:56
Closing as works as designed, since FMI is by design a same process integration technology to minimise overhead, and known methods exist to use FMI across process boundaries.

**Closed as completed by pmai** 2018-02-15 16:56 UTC
Labels: quality
